### ISSUE TITLE
Auto sync from template repo when template repo is private are not working

### ISSUE THREAD

**Issue by pzaino** [RISC-OS-Community/StandardRepoTemplate#5]
# Description

So been testing the first automation which will (every Friday) resync all our repos with the changes (if any) from StandardRepoTemplate. 

This will ensure that if we need to change something in one of the docs from the template it will get updated on all repositories and the automation will generate a pull request out of the changes for us to review and merge.

Now the problem is that, if I set the Template repository to private, then the automation fails an dit seems to be a problem related to the way github generates the tokens for the actions.

I am not an expect, but it sounds like we may have to use a static token for a private repository? 

So can anyone have a look into this?

# To reproduce

1. Set this repository (StandardRepoTemplate) as private
2. On the repository ExampleRepository go to Action and run the action "Sync Changes from template"
3. Check for the result (make sure you click on the details to see the error)

# Expected behaviour

It should have worked as when StandardRepoTemplate is public

# Screenshots

No screenshots.

# Traceback

```
Determining the default branch
  Retrieving the default branch name
  Not Found
  Waiting 16 seconds before trying again
  Retrieving the default branch name
  Not Found
  Waiting 17 seconds before trying again
  Retrieving the default branch name
  Error: Not Found
```

# RISC OS Release

This is a github error, so no RISC OS involved.

# Loaded Modules

none

# Platform

[] - Acorn Archimedes 3x0/4x0 series (with ARM 3)
[] - Acorn A5000
[] - Acorn A30x0 or A4000 series (with ARM250)
[] - Acorn RiscPC 600 (with ARM 610)
[] - Acorn RiscPC 700 (with ARM 710)
[] - Acorn RiscPC StrongARM
[] - Acorn RiscPC with Kinetic or Castle RiscPC
[] - Acorn A7000/A7000+ or Castle A7000+
[] - Raspberry Pi1 (model A or B)
[] - Raspberry Pi2 (all models)
[] - Raspberry Pi3 (all models)
[] - Raspberry Pi4 (Please specify the amount of RAM in the Other Field at the end of this list)
[] - Raspberry Pi400 (Please specify the amount of RAM in the Other field at the end of this list)
[] - i.MX6 / Mini.M
[] - PineBook / ARMBook
[] - PandaBoard
[] - WandaBoard or Quadro
[] - Titanium board
Other:
GitHub.com

# Other possible details
none

**Comment by pzaino** [comment]
@skymandr not sure if you have time, but if you know a good way to fix this it may be helpful.

My understanding is that we may have to use some static token or something (instead of the dynamic tokens generated by github at run time), but I may be wrong.

**Comment by skymandr** [comment]
I can try to look into it, but why does the template repo have to be private?

**Comment by pzaino** [comment]
No special reasons except to avoid people from try to use it as a regular repo, that all, so it's not a major issue, but if you have any idea that would help :)

So I am going to assign this one to you, no hurry. Whenever you have time to look into it that'll be good, thanks a lot!

**Comment by skymandr** [comment]
All right, I'll have a look, but if it causes hassle, I think that making it non-private is probably the way to go.
